import { test, expect, type Page } from '@playwright/test';
import { BASE_PATH } from '../playwright.config';
import { db } from '../src/server/db';
import { mkdirSync } from 'node:fs';
const shots = '.impeccable/review/navigation';
mkdirSync(shots, { recursive: true });
async function register(page: Page) {
  const email = `navigation-philosophy-${Date.now()}-${Math.random()}@seder.test`;
  await page.goto(`${BASE_PATH}/register?next=%2Fapp%2Ftoday`);
  await page.getByLabel('שם', { exact: true }).fill('בדיקת ניווט');
  await page.getByLabel('אימייל', { exact: true }).fill(email);
  await page.getByLabel('סיסמה', { exact: true }).fill('navigation-test-123');
  await page.getByRole('button', { name: 'יצירת חשבון', exact: true }).click();
  await page.waitForURL('**/app/today');
  await page.getByTestId('whatsapp-introduction').getByRole('button', { name: 'לא עכשיו', exact: true }).click();
  return db.user.findUniqueOrThrow({ where: { email } });
}

test('desktop keeps daily lists visible, disclosure persists and navigation identifies labels and focus', async ({ page }) => {
  const user = await register(page);
  await db.label.createMany({ data: Array.from({ length: 25 }, (_, i) => ({ userId: user.id, name: `סימון ${i+1}`, position: `b${String(i).padStart(2,'0')}` })) });
  const owner = await db.user.create({data:{name:'שותף לבדיקה',email:`navigation-owner-${user.id}@seder.test`,passwordHash:user.passwordHash}});
  const shared = await db.project.create({data:{userId:owner.id,name:'פרויקט משותף',position:'c0',color:'plum',members:{create:{userId:user.id}}}});
  await page.goto(`${BASE_PATH}/app/today`);
  await expect(page.locator('.rail').getByText('שותפו איתי',{exact:true})).toBeVisible();
  await expect(page.locator('.rail').getByRole('link',{name:shared.name,exact:true})).toHaveAccessibleDescription('0 משימות פתוחות, שותף איתכם');
  await page.setViewportSize({ width: 1440, height: 900 });
  const rail = page.locator('.rail');
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: `${shots}/desktop.png`, animations: 'disabled' });
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
  await page.screenshot({ path: `${shots}/desktop-dark.png`, animations: 'disabled' });
  await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
  const primary = page.getByTestId('primary-navigation');
  const before = (await primary.boundingBox())!.y;
  const labels = rail.getByRole('button', { name: 'תוויות', exact: true });
  await labels.click();
  await rail.locator('nav').evaluate(node => { node.scrollTop = node.scrollHeight; });
  expect((await primary.boundingBox())!.y).toBeCloseTo(before, 1);
  await expect(primary.getByRole('link', { name: 'היום', exact: true })).toBeInViewport();
  await expect(rail.getByRole('link', { name: 'סימון 25', exact: true })).toBeInViewport();
  await labels.click();
  await page.reload();
  await expect(labels).toHaveAttribute('aria-expanded', 'false');
  const label = await db.label.findFirstOrThrow({ where: { userId: user.id, name: 'סימון 25' } });
  await page.goto(`${BASE_PATH}/app/label/${label.id}`);
  await expect(labels).toHaveAttribute('aria-expanded', 'true');
  await expect(rail.getByRole('link', { name: 'סימון 25', exact: true })).toHaveAttribute('aria-current','page');
  await expect(page.locator('.workspace-bar')).toContainText('תוויות');
  await expect(page.locator('.workspace-bar')).toContainText('סימון 25');
  await rail.getByRole('link',{name:'מיקוד ותכנון',exact:true}).click();
  await expect(page.locator('.workspace-bar')).toContainText('מיקוד ותכנון');
  await page.goBack();
  await expect(rail.getByRole('link', { name: 'סימון 25', exact: true })).toHaveAttribute('aria-current','page');
  await page.goForward();
  await expect(page.locator('.workspace-bar')).toContainText('מיקוד ותכנון');
  await page.setViewportSize({width: 1440, height:900});
  await page.getByRole('button',{name:'צמצום הסרגל',exact:true}).click();
  await expect.poll(async()=> (await rail.boundingBox())!.width).toBe(68);
  await expect(primary.getByRole('link',{name:'היום',exact:true})).toHaveAccessibleName('היום');
  await primary.getByRole('link',{name:'היום',exact:true}).click();
  await expect(page.getByRole('heading',{name:'היום',exact:true,level:1})).toBeVisible();
  await page.getByRole('button',{name:'פתיחת הסרגל',exact:true}).click();
});

test('mobile Browse keeps orientation, counts, capture, collections and settings reachable', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width:390,height:844 }, isMobile:true,hasTouch:true,locale:'he-IL',timezoneId:'Asia/Jerusalem' });
  const page = await context.newPage();
  const user = await register(page);
  await db.task.create({ data: { userId:user.id,title:'משימת תיבה',position:'a0',whenBucket:'ANYTIME' } });
  await page.reload();
  const tabs=page.getByRole('navigation',{name:'ניווט מהיר'});
  await expect(tabs.getByRole('link',{name:'תיבה',exact:true})).toHaveAccessibleDescription('משימה פתוחה אחת');
  await page.screenshot({path:`${shots}/mobile-tabs.png`,animations:'disabled'});
  for (const width of [390,320,576]) {
    await page.setViewportSize({width,height:844});
    const menu=tabs.getByRole('button',{name:'רשימות',exact:true});
    await menu.click();
    await expect(menu).toHaveAttribute('aria-expanded','true');
    await expect(tabs.getByRole('link',{name:'היום',exact:true})).toHaveAttribute('aria-current','page');
    await expect(page.locator('main')).toHaveAttribute('inert','');
    await expect(page.locator('.mobile-add')).toBeHidden();
    const rail=page.locator('.rail');
    if (width === 390) await page.screenshot({path:`${shots}/mobile-default.png`,animations:'disabled'});
    const labels=rail.getByRole('button',{name:'תוויות',exact:true});
    if(await labels.getAttribute('aria-expanded')==='false') await labels.click();
    await expect(menu).toHaveAttribute('aria-expanded','true');
    await expect(rail.getByRole('link',{name:'טלפון',exact:true})).toBeVisible();
    await expect(rail.getByRole('link',{name:'היום',exact:true})).toBeHidden();
    await page.evaluate(()=>document.fonts.ready);
    await page.screenshot({path:`${shots}/mobile-${width}.png`,animations:'disabled'});
    if (width === 390) {
      await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
      await page.screenshot({path:`${shots}/mobile-dark.png`,animations:'disabled'});
      await page.evaluate(() => { document.documentElement.dataset.theme = 'light'; });
    }
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.keyboard.press('Escape');
    await expect(menu).toBeFocused();
    await expect(page.locator('main')).not.toHaveAttribute('inert','');
  }
  await page.setViewportSize({width:390,height:844});
  await tabs.getByRole('button',{name:'רשימות',exact:true}).click();
  await page.locator('.rail').getByRole('link',{name:'לוח שנה',exact:true}).click();
  await expect(tabs.getByRole('button',{name:'רשימות',exact:true})).toHaveAttribute('aria-current','page');
  await expect(tabs.getByRole('button',{name:'רשימות',exact:true})).toHaveAttribute('aria-expanded','false');
  await page.goBack();
  await expect(tabs.getByRole('link',{name:'היום',exact:true})).toHaveAttribute('aria-current','page');
  await tabs.getByRole('button',{name:'רשימות',exact:true}).click();
  await page.locator('.rail').getByRole('link',{name:'הגדרות',exact:true}).click();
  await expect(page.getByRole('heading',{name:'הגדרות',exact:true,level:1})).toBeVisible();
  await expect(tabs).toBeHidden();
  const tablet = await browser.newContext({storageState:await context.storageState(),viewport:{width:1024,height:900},hasTouch:true,locale:'he-IL',timezoneId:'Asia/Jerusalem'});
  const tabletPage=await tablet.newPage();
  await tabletPage.goto(`${BASE_PATH}/app/today`);
  expect(await tabletPage.evaluate(()=>matchMedia('(pointer:coarse)').matches)).toBe(true);
  const controls=await tabletPage.locator('.rail-link:visible,.rail-search,.rail-section-toggle:visible,.rail-section-actions button').evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect().height));
  expect(controls.every(height=>height>=44)).toBe(true);
  await tabletPage.screenshot({path:`${shots}/tablet-touch.png`,animations:'disabled'});
  await tablet.close();
  await page.getByRole('link',{name:'חזרה למשימות',exact:true}).click();
  await page.setViewportSize({width:740,height:390});
  await tabs.getByRole('button',{name:'רשימות',exact:true}).click();
  await page.locator('.rail-nav').evaluate(node=>{node.scrollTop=node.scrollHeight;});
  await expect(page.locator('.rail').getByRole('link',{name:'מיקוד ותכנון',exact:true})).toBeInViewport();
  await page.screenshot({path:`${shots}/mobile-landscape.png`,animations:'disabled'});
  await context.close();
});
